version: "3"

services:
  db:
    image: postgres
    container_name: cst_postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "condition_tracker"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    container_name: cst_redis
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  celery-worker:
    build: .
    container_name: cst_celery-worker
    command: celery -A config worker -l INFO
    depends_on:
      api:
        condition: service_started

  celery-beat:
    build: .
    container_name: cst_celery-beat
    command: celery -A config beat -l info -S django
    depends_on:
      celery-worker:
        condition: service_started


  telegram_bot:
    build: .
    container_name: cst_telegram_bot
    command: python3 manage.py telegram_bot
    depends_on:
      api:
        condition: service_started


  api:
    container_name: cst_api
    build:
      context: .
    links:
      - db
    command: bash -c "
      python3 manage.py migrate && 
      python3 manage.py collectstatic --noinput && 
      python3 manage.py runserver 0.0.0.0:8000
      "
    tty: false
    volumes:
      - .:/mood_tracker
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy