# Generated by Django 4.2.4 on 2023-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('respondent_tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID респондента')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('chat_tg_id', models.BigIntegerField(verbose_name='Чат ID телеграмма')),
                ('last_report_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата отправки отчета')),
            ],
            options={
                'verbose_name': 'респондент',
                'verbose_name_plural': 'респонденты',
            },
        ),
    ]
