# Generated by Django 4.2.4 on 2023-08-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moda_mood', models.IntegerField(verbose_name='мода настроения')),
                ('moda_energy', models.IntegerField(verbose_name='мода энергии')),
                ('average_mood', models.FloatField(verbose_name='среднее настроения')),
                ('average_energy', models.FloatField(verbose_name='среднее энергии')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания отчета')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent', verbose_name='Респондент')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
            },
        ),
    ]
