# Generated by Django 4.2.4 on 2023-08-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Настроение')),
                ('energy', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Энергия')),
                ('poll_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата опроса')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent', verbose_name='Респондент')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
    ]
